let wordsArray = [
    "html",
    "css",
    "javascript",
    "jquery",
    "ajax",
    "react",
    "angular",
    "node js",
    "express js",
    "redux",
    "chart js",
    "bootstrap",
    "php",
    "yii",
    "laravel",
    "codigniter",
    "mysql",
    "mongo db",
    "asp .net",
    "java",
    "python",
    "django",
    "ruby",
    "c++",
    "webpack",
    "hammer js",
    "http",
    "server",
    "programming",
    "artificial inteligence",
    "development",
    "website",
    "app",
    "frontend",
    "backend",
    "cross platform",
    "xml",
    "api",
    "algorithm",
    "ssl",
    "enrypt",
    "decrypt",
    "code",
   ];

const reservedkeys =['Space',
     
   'ArrowLeft', 'ArrowUp', 
   'ArrowDown', 'ArrowRight',
    'Delete','Shift', 'Control', 'Escape',
   'OS'];